### ISSUE TITLE
Support real-valued zooms for WOF data.

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/tilequeue#110]
The WOF import code currently [considers it an error](https://github.com/tilezen/tilequeue/blob/961d31c4dbb3ea008317c6760b7c7a2f0289fe7c/tilequeue/wof.py#L293-L308) if the `mz:min_zoom` or `mz:max_zoom` parameters are not integers. However, they are [allowed to be real numbers](https://github.com/tilezen/vector-datasource/issues/976#issuecomment-241909742) although the [docs are silent](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/mz.md#max_zoom) on the matter! 

Note that tilezen/vector-datasource#976 should have been completed before this, so that the schema is ready to take the real numbers.

**Comment by nvkelso** [comment]
Good catch! WOF docs updated in https://github.com/whosonfirst/whosonfirst-properties/commit/56bcf9f4f4905b4fb5d4724a7cd16e270a7a19d6#diff-a0a3ab804180a562fb13a7aecba9d4a1.
