### ISSUE TITLE
Can't connect to S3 for tile storage

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [tilezen/tilequeue#117]
Initially I've mentioned this problem [here](https://github.com/tilezen/vector-datasource/issues/1088#issuecomment-250698737), but tilequeue repo is more proper for this.

I was trying to set up s3 as the store, however I wasn't able due to:

``` bash
  File "/.../Mapzen/env/local/lib/python2.7/site-packages/boto/auth.py", line 941, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
```

I'm sure I did provide valid `aws_access_key_id` and `aws_secret_access_key`, but something tells me it may not be enough. I have other apps (written for [node.js](https://nodejs.org)) where I use [s3](https://github.com/andrewrk/node-s3-client) module and so there I need to provide additional `region` param (e.g. region = "us-west-2") otherwise access key/secret access key would not suffice.

If I'm ever going to have a moment, I'll check if I can submit a pr for this. Can't promise though :)

**Comment by rmarianski** [comment]
To verify that this is the issue, can you try setting the [default region environment variable](http://boto3.readthedocs.io/en/latest/guide/configuration.html), `AWS_DEFAULT_REGION`, to see if it helps?

**Comment by nvkelso** [comment]
@ktrzeciaknubisa is this still a problem for you?

**Comment by ktrzeciaknubisa** [comment]
I'm sorry, I can't really check, because I disabled the machine I was testing it on. Feel free to close this item if you like so.

**Comment by nvkelso** [comment]
No worries. I'll close this issue. Please make a new issue if you hit another problem in the future.
