### ISSUE TITLE
Memory usage while seeding

### ISSUE THREAD

**Issue by hriad** [tilezen/tilequeue#125]
Hello, 
I'm trying to seed based on a bbox ([-17.628501036130604, 12.780733971799824, 29.499734490797476, 38.04327800816175]) and tiles from zoom level 1 to 16. I'm running this on a 16gb server, but the seeding never completes as tilequeue end up eating all the available memory and finally the server crashes. The queue type is set to file. Is it supposed to consume this much memory?

**Comment by rmarianski** [comment]
The tiles are generated in a lazy fashion, meaning not in memory, but the final step tries to unique everything, which actually does put everything in memory to do so. I bet that if that unique step were omitted, you wouldn't run into memory problems. If you're feeling up to it, you can try removing the [uniquify generator line](https://github.com/tilezen/tilequeue/blob/2d9f041e96159a3ed838678dbef127816682a3e6/tilequeue/command.py#L255) and return back just the `combined_tiles`.

Trying to generate a unique list can be useful as a optimization, but there are cases like yours when you don't want to do it. This should probably be exposed as a configuration option.

By the way, if my back of the envelope math is right, that's about 50 million tiles. That's most likely going to be too much work for a single instance to run through anyway.

**Comment by rmarianski** [comment]
Unfortunately, this is a little more involved than just that one line change, because the caller calls `list` on it to get the count beforehand, which will also realize the entire list into memory.

**Comment by rmarianski** [comment]
I've created #126 and #127 as follow ups.

**Comment by nvkelso** [comment]
@rmarianski should we close this issue in favor of the two new issues you created?

**Comment by rmarianski** [comment]
Sure, #126 specifically should resolve this.
