### ISSUE TITLE
Remember queue source when reading messages

### ISSUE THREAD

**Issue by nvkelso** [tilezen/tilequeue#134]
_From @rmarianski on December 16, 2016 16:41_

For messages that get enqueued in the custom top priority queue, the current behavior is try to acknowledge them in a different queue based on its zoom level, which fails.

Instead of calculating the queue on acknowledgement, it should get threaded through the pipeline.

_Copied from original issue: tilezen/vector-datasource#1146_

**Comment by nvkelso** [comment]
_From @rmarianski on December 16, 2016 20:49_

Not sure why I created this issue in vector-datasource. The tilequeue repo would have been more appropriate.

**Comment by rmarianski** [comment]
Deployed to prod.
