### ISSUE TITLE
Explore adding priorities to tile processing

### ISSUE THREAD

**Issue by rmarianski** [tilezen/tilequeue#18]
All tiles are currently processed without any priority given to them. Priorities would allow us to control processing in more flexible ways, and may even increase throughput.

One way to add this would be to add support for multiple queues, where the queues are queried in a configured order. We would need to update:
- intersect process to enqueue tiles to the appropriate queue
- worker processor that pulls work from the queue should ask for tiles from queues in priority order
- seed process - probably best to seed tiles using the same strategy

Assuming we always want to have tiles enqueued using this strategy, it would be best to create a new tilequeue queue implementation that had this logic baked in. The other components would not need to change then. Even if we did need to support different behavior based on context, we could add in keyword arguments that certain queue implementations could honor, and others would ignore.

**Comment by nvkelso** [comment]
Straw man proposal:

- Escalation queue immediately
- Zooms 15-16+ ASAP after escalation queue
- Zooms 13-14 hourly
- Zooms 11-12 daily
- Zooms 0-10 weekly

**Comment by nvkelso** [comment]
Add pager duty alert for items in queue for longer than 1 week.

**Comment by pnorman** [comment]
> Straw man proposal:

A generic ability to have queues sounds more useful - some deployments could have different tiers of customers

**Comment by nvkelso** [comment]
@pnorman definitely – the priority queues should be initially for normalizing data updates but should be extendable towards different "areas of interest" and frequency cycles per customer interest. We could even implement tile pack support this way.

**Comment by nvkelso** [comment]
- SQS pricing is $0.40 per million requests ($0.00000040 per request). 
- A single request can have from 1 to 10 messages, up to a maximum total payload of 256 KB.
- See more: https://aws.amazon.com/sqs/pricing/

Looks like we do 250k to 500k per day on average (but spike up to 6mm one day in last 2 weeks). **Let's say 1mm / day per queue = $12 / month.** 

If we have **5 queues** in the new priority system then that'd be **$60 / month**. Our prod deploy costs would remain consistent (and they'd just be in a single priority queue). 

We could adjust these costs by changing a time interval, but estimated cost is low enough to not worry about that now.

**Comment by pnorman** [comment]
What about those not running tilequeue on AWS?

**Comment by nvkelso** [comment]
@pnorman Mapzen uses AWS to run Tilequeue currently and will for the foreseeable future. How are you implementing this bit if you're not on AWS?

**Comment by pnorman** [comment]
> @pnorman Mapzen uses AWS to run Tilequeue currently and will for the foreseeable future. How are you implementing this bit if you're not on AWS?

By following the instructions on https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service

**Comment by nvkelso** [comment]
Are you using tilequeu as a library (that’s generally what’s happening in
the wiki) or to process OSM data updates into your existing cache of tiles?

**Comment by pnorman** [comment]
Just what's on the wiki. I'm still working towards a full production setup with diffs and all the bells and whistles.

**Comment by rmarianski** [comment]
After seeding in dev (z11-16 for sf and nyc), the breakdown looks expected:

![priority-queue](https://cloud.githubusercontent.com/assets/53770/20854711/13f915c8-b8c4-11e6-9b52-77987ccd80fd.png)

**Comment by rmarianski** [comment]
And it seems like the priority queue behavior is working as expected in the order that it draws from the queues:

![priority-queue-2](https://cloud.githubusercontent.com/assets/53770/20855127/edc3ab4e-b8c7-11e6-9037-5dec79f687a5.png)

**Comment by rmarianski** [comment]
We should also enqueue files back down to zoom level 0 instead of stopping at 11.
