### ISSUE TITLE
Publish tilequeue to pypi

### ISSUE THREAD

**Issue by nvkelso** [tilezen/tilequeue#220]
Sister issue to https://github.com/tilezen/tileserver/issues/51.

**Comment by nvkelso** [comment]
(Not clear if we should do this with our Docker work that's wrapping up.)

**Comment by pnorman** [comment]
I think it should be done, not all deployments will necessarily be using docker, and the hard work of packaging it is already being done, it's just uploading it to pypi.

**Comment by nvkelso** [comment]
This is done: https://pypi.python.org/pypi/tilequeue/1.9.1.
