### ISSUE TITLE
Should zoom ranges be inclusive or exclusive of the end?

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/tilequeue#235]
Following on from https://github.com/tilezen/tilequeue/pull/234#discussion_r131861499, should we generally use ```{ zoom_start: 0, zoom_end: 5 }``` to mean zooms 0, 1, 2, 3, 4 and 5, or just 0, 1, 2, 3 and 4?

In favour of inclusive end-ranges:

* They might be more intuitive.

In favour of exclusive end-range:

* It's easier to see when a series of ranges meet with no gaps, as the end of one range should be the same as the start of the next.

**Comment by nvkelso** [comment]
Agree it's confusing. I had similar quandary while adding min_zoom values Natural Earth and also settled on exclusive zoom ranges. It get's more confusing when you take max_zoom into account!

**For example:** a feature with `min_zoom` = **2** and `max_zoom` of **5** should be included at zoom 2, 3, and 4, but not 5.

Suggest no-change to the Tilezen logic.

**Comment by zerebubuth** [comment]
Either would be a change to the logic - we currently do it both ways in different parts of the code!

**Comment by nvkelso** [comment]
Eek! +1 for making them consistent.

**Comment by pnorman** [comment]
Some other conventions are

- t-rex does inclusive on the low end and exclusive on the high end, e.g.

```toml
[[tileset.layer.query]]
minzoom = 0
maxzoom = 5
sql = """..."""
[[tileset.layer.query]]
minzoom = 5
sql = """..."""
```

- OpenStreetMap Carto [CartoCSS guidelines](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#cartocss-style-guidelines) have inclusive on the low end and exclusive on the high, and this is explicit with how the language is written
```mss
  ::lower-mid-zoom[zoom >= 10][zoom < 11] { image-filters: scale-hsla(0,1,0,1,0.6,0.95,0,1); }
```

- Conventional Mapnik queries with a `z` function do inclusive on the low end and exclusive on the high, e.g. 
```sql
WHERE z(!scale_denominator!) >= 5 AND z(!scale_denominator!) < 10
```

I prefer exclusive ranges. Zoom is not necessarily an integer, even though at this point in the architecture it may be. In styles and rendering you have to deal with zooms like 4.9, so you need exclusive ranges, and that makes it easier to use exclusive ranges everywhere.

**Comment by zerebubuth** [comment]
Follow-up: https://github.com/tilezen/vector-datasource/issues/1367

That's the only place I've found so far which makes widespread use of `end_zoom` to mean `zoom <= end_zoom`. If anyone has found any more examples, please link them back here.

**Comment by nvkelso** [comment]
Closed via https://github.com/tilezen/vector-datasource/issues/1367.
