### ISSUE TITLE
Push v1.8.0 to pypi

### ISSUE THREAD

**Issue by pnorman** [tilezen/tilequeue#263]
1.8.0 isn't on PyPi. It'd be nice to have it there because this was the version that was current when 2.8.0 of tileserver was released.

The code historian in me would like all versions, but 1.8.0 is the only one which is useful for practical reasons.

**Comment by nvkelso** [comment]
@rmarianski Can you look at publishing the missing v1.8.0 to PyPi, please?

**Comment by rmarianski** [comment]
I published the v1.8.0 version

https://pypi.python.org/pypi/tilequeue/1.8.0
