### ISSUE TITLE
Error storing ... Name or service not known

### ISSUE THREAD

**Issue by elwin-jacellc** [tilezen/tilequeue#325]
Hi, running on ec2 and able to dump tiles to file, but when I configure to store to s3, I get the following error:

`2018-01-10T04:52:16+0000 Error storing: 2/1/0 - Traceback (most recent call last): |   File "/home/ubuntu/vector-datasource/env/local/lib/python2.7/site-packages/tilequeue/worker.py", line 342, in __call__    did_store = async_job.get() |   File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get    raise self._value | gaierror: [Errno -2] Name or service not known`

I've tried with an s3 bucket in us-west-2 and us-east-1, same effect. Appreciate any guidance.

**Comment by rmarianski** [comment]
This looks like a dns error to me. Are you using an s3 store?

**Comment by elwin-jacellc** [comment]
Yes. Trying to store to S3. Here are snippets from our config.yaml

`store:
  type: s3 # Can also be `directory`, which would dump the tiles to disk.
  name: jace.design.tiles/test/
  # The following store properties are s3 specific.
  path: osm
  reduced-redundancy: true
  date-prefix: 19851026`

`rawr:
sink:
    bucket: jace.design.tiles
    region: us-east-1
    prefix: s3
    suffix: .zip`

We run the following commands:

`tilequeue seed --config config.yaml`

then

`tilequeue process --config config.yaml`

**Comment by rmarianski** [comment]
Ah, thanks for sharing the config. In the `store` part, the `name` should just be the bucket name, and not the full path into it. To put it in a `/test` prefix, you can just override the `date_prefix` part. I'm not 100% about it, but I expect that it doesn't actually have to be a date. Eg, try this:

```yaml
store:
  type: s3
  name: jace.design.tiles
  date_prefix: test
```

Just to check if you can write anything at all, here's a simple script:

```python
from tilequeue.command import _make_store
from tilequeue.config import make_config_from_argparse
from tilequeue.format import json_format
from tilequeue.tile import deserialize_coord


cfg_path = 'config.yaml'
with open(cfg_path) as fh:
    cfg = make_config_from_argparse(fh)
store = _make_store(cfg)
tile_data = 'data'
coord = deserialize_coord('1/1/1')
format = json_format
layer = 'all'
store.write_tile(tile_data, coord, format, layer)
```

**Comment by elwin-jacellc** [comment]
Got it. Seems to be a problem with buckets with . (dots)

https://github.com/boto/boto/issues/2836

**Comment by rmarianski** [comment]
Yea, I was going to suggest that next. We use dashes `-` as separators for this reason. Glad you got it working!
