### ISSUE TITLE
Skip empty tiles

### ISSUE THREAD

**Issue by elwin-jacellc** [tilezen/tilequeue#326]
Let's say we'd like to generate tiles for zoom level 15, but only for the building layer. I think we can change the queries.yaml file to remove all the other layers, but the question we have is whether tilequeue will still generate files for empty tiles (i.e. tiles where there are no buildings). We'd like to generate and store these tiles in s3, so cost becomes an issue at higher zoom levels. Thanks.

**Comment by rmarianski** [comment]
It would still save the tiles on s3, even when the buildings or all layers were empty.

If you're willing to dig into the code to make this change, I wouldn't guess that it would be too difficult to make. The place to start would be in [worker.py](https://github.com/tilezen/tilequeue/blob/master/tilequeue/worker.py). I'd look into creating some special type of marker or sentinel, maybe can even be the `None` value, to identify the case when the tile is empty. Then subsequent stages in the pipeline can know that it should be ignored.

**Comment by elwin-jacellc** [comment]
Gotcha. Thanks.

**Comment by elwin-jacellc** [comment]
What's the best way to test whether the tile is empty? `formatted_tiles, extra_data` ?

**Comment by rmarianski** [comment]
Problem is that once it's formatted it's hard to tell. Would probably make sense to break apart the `process`ing and the `format`ing, kind of how it's done [in](https://github.com/tilezen/tileserver/blob/a8be93ea911ef5b6a9511e482af687971d18e6c6/tileserver/__init__.py#L245-L251) [tileserver](https://github.com/tilezen/tileserver/blob/a8be93ea911ef5b6a9511e482af687971d18e6c6/tileserver/__init__.py#L261-L271).

The result of the `process_coord_no_format` function, ie `feature_layers`, will be a structure that contains the features within it (IIRC each "feature_layer" is a dict that some metadata about it, like its name, and the features live in the "features" key).
