### ISSUE TITLE
Don't re-PUT unchanged items

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/tilequeue#80]
At the moment, a tile is always stored in S3 after it is rendered. The majority of renders over the long term are caused by tile expiries. `osm2pgsql` has to be very conservative when generating tile expiries, and will expire features on which any tag has changed or the whole interior and/or boundary of large features if any point on them changes. This can potentially lead to re-rendering tiles with the exact same result as the existing tile.

Filtering these out before rendering seems pretty hard - it would mean examining the changes to see if they match the queries and survive the tile transform pipeline.

However, filtering them out just before storing them would be pretty easy: Do a GET request just before the PUT and if the content is identical then don't do the PUT. In the simple case this is a win if 8% or more of re-renders are identical, but that percentage gets lower the more we amplify our writes with more formats and replica regions.

**Comment by bcamper** [comment]
Nice idea.

**Comment by nvkelso** [comment]
This is live on prod now.
